name: C++ Build Workflow

on: [push, pull_request]

jobs:
  build:
    name: Build C++ Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install GCC
      run: sudo apt-get install g++

    - name: Build SalemanAI
      run: |
        g++ -o SalemanAI AI/SalemanAI.cpp
        ./SalemanAI

    - name: Build SalemanBruteforce
      run: |
        g++ -o SalemanBruteforce bruteforce/SalemanBruteforce.cpp
        ./SalemanBruteforce
